#!/bin/bash

# this is specific to my test env; you may want to change it

set -e

cd /home/g3

if [ "$1" = "-c" ]
then
    rm -rf .gito* gito* repositories proj* bin
    mkdir bin
    cp ~/.ssh/id_rsa.pub ~/.ssh/admin.pub

    cd g3; cp -a gito* Gito* t/glt t/gito* ~/bin
    gitolite setup -a ${2:-admin} -pk ~/.ssh/admin.pub
else
    cd g3; cp -a gito* Gito* t/glt t/gito* ~/bin
    gitolite setup
fi
