#!/bin/bash

# WARNING: USES BASH FEATURES TO AVOID A TEMP FILE; CAN BE FIXED IF NEEDED

. $(dirname $0)/adc.common-functions

get_rights_and_owner gitolite-admin
[ -z "$perm_write" ] && die "just *what* are you trying to pull, young man?"

op=$1
shift

locs=
while [ -n "$1" ]
do
    case $1 in
        '@all' )
            locs="$locs $HOME"
            ;;
        * )
            loc="$GL_REPO_BASE_ABS/$1.git"
            [ -d $loc ] && locs="$locs $GL_REPO_BASE_ABS/$1.git"
            [ -d $loc ] || echo "ignoring $1..."
            ;;
    esac
    shift
done

[[ -z "$locs" ]] && die "give me '@all' or some reponame"

case $op in
    en|enable )
        for l in $locs
        do
            rm -fv $l/.gitolite.down
        done
        ;;
    dis|disable )
        # bashism
        read msg <<<$(cat)
        echo disabling following locations with message:
        echo $msg
        echo
        for l in $locs
        do
            echo $msg > $l/.gitolite.down
            echo $l
        done
        ;;
    * )
        die "argument 1 must be 'en' or 'dis'"
        ;;
esac
