#!/bin/bash

export TESTDIR=$PWD

cd
rm -rf gitolite-admin td
tar xf rollback.tar
mkdir td

scp -q $TESTDIR/rollback.server gitolite-test@localhost:rollback || { echo scp failed; exit 1; }
ssh gitolite-test@localhost ./rollback $GQT
