#!/bin/sh

# Use this to re-establish gitolite admin access when admin key(s) are lost.

# RUN THIS ON THE SERVER, NOT THE CLIENT!  (so you need shell access to the
# server; even with password is fine)

# HOW TO USE (substitute your admin name for "sitaram" below)
# - make yourself a new keypair on your workstation
# - copy the pubkey to the server, call it "sitaram.pub" and put it in $HOME
# - run this command:
#       ~/.gitolite/src/gl-emergency-addkey sitaram emergency sitaram.pub

# this will add a new key called sitaram@emergency.pub.  Since the "userid"
# that key pertains to is "sitaram", whoever has the private key for this now
# has the same rights as "sitaram"

# WARNING: ABSOLUTELY NO ARGUMENT CHECKING DONE
# WARNING: NEWER GITS ONLY ON SERVER SIDE (for now)

# ENDHELP

# we can't use this program unless it was installed using gl-easy-install
GL_PACKAGE_CONF=$( cd; perl -e 'do ".gitolite.rc"; print $GL_PACKAGE_CONF' )
if [ -n "$GL_PACKAGE_CONF" ]
then
    cat <<EOF
    This is not a "from-client method" install; you cannot add an emergency
    key using this program.

    Please do the following (change "sitaram" below to whatever your admin
    username is):

      - get your *new* public key to the server
      - call it "sitaram.pub"; put it in \$HOME
      - run "gl-setup \$HOME/sitaram.pub"
EOF
    exit 1
fi

[ -z "$1" ] && { perl -pe "s(\\\$0)($0); last if /ENDHELP/" < $0; exit 1; }

set -e

cd

REPO_BASE=$(  perl -e 'do ".gitolite.rc"; print $REPO_BASE'  )
GL_ADMINDIR=$(perl -e 'do ".gitolite.rc"; print $GL_ADMINDIR')

cd; cd $GL_ADMINDIR/keydir; pwd
cp -v $3 $1@$2.pub

cd; cd $REPO_BASE/gitolite-admin.git; pwd
# XXX FIXME TODO -- fix this to work with older gits also
GIT_WORK_TREE=$GL_ADMINDIR git add keydir
GIT_WORK_TREE=$GL_ADMINDIR git commit -m "emergency add $1@$2.pub"

cd $GL_ADMINDIR
src/gl-compile-conf
